spring.application.name=LinguRemi

# PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-odd-lab-ac9sgv65-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_U4rn1jOAhbRl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Uploads
spring.web.resources.static-locations=file:${user.dir}/uploads/

# JWT
api.security.token.secret=${JWT_SECRET:my-secret-key}

server.port=${PORT:8080}