spring.application.name=LinguRemi

# PostgreSQL Neon
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Mercado Pago Api
mercadopago.access.token=${MERCADO_PAGO_ACCESS_TOKEN}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Uploads
spring.web.resources.static-locations=file:${user.dir}/uploads/

# JWT
api.security.token.secret=${JWT_SECRET:my-secret-key}

#Logs
logging.file.name=logs/linguremi.log

server.port=${PORT:8080}